# Generated by Django 6.0 on 2026-01-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='')),
                ('document', models.FileField(upload_to='')),
            ],
        ),
    ]
