# Generated by Django 6.0 on 2026-01-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practice_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
